### ISSUE TITLE
issue copying gif outputs into preview

### ISSUE THREAD

**Issue by eelucio** [freva-org/freva-legacy#136]
When copy/transforming output images/animations into share/preview there is a problem with GIF images, they are resized and only the first (?) frame is copied, e.g. https://www.xces.dkrz.de/history/923870/results/

[In principle it should be copying](https://github.com/FREVA-CLINT/freva/blob/525ec6cbe632836c48e0d44baf8af437d5cde1b9/src/evaluation_system/api/plugin.py#L657):
```python
                if ext in ".jpg .jpeg .png .gif .mp4 .mov".split():
                    metadata["type"] = "plot"
                    metadata["todo"] = "copy"
``` 

[this leads to](https://github.com/FREVA-CLINT/freva/blob/525ec6cbe632836c48e0d44baf8af437d5cde1b9/src/evaluation_system/api/plugin_manager.py#L679):
```python
        if todo == "copy":
            ext = os.path.splitext(file_name)[-1]
            target_name = _preview_unique_file(plugin_name, ext, metadata)
            todo_list.append((_preview_copy, file_name, target_name))
            metadata["preview_path"] = target_name
            result_list.append(target_name)
```

[then to](https://github.com/FREVA-CLINT/freva/blob/525ec6cbe632836c48e0d44baf8af437d5cde1b9/src/evaluation_system/api/plugin_manager.py#L560):
```python
    extension = Path(source_path).suffix
    supported = Image.registered_extensions()
    if extension in supported and supported[extension] not in IMAGE_RESIZE_EXCEPTIONS:
        _preview_convert(source_path, dest_path)
    else:
        shutil.copyfile(source_path, dest_path)
```

[which looks into](https://github.com/FREVA-CLINT/freva/blob/525ec6cbe632836c48e0d44baf8af437d5cde1b9/src/evaluation_system/api/plugin_manager.py#L77):
```python
IMAGE_RESIZE_EXCEPTIONS = ["PDF", "HDF5", "GRIB"]
```
 
wouldn't this mean that we are converting everything that is not PDF,HDF5,GRIB ?

**Comment by antarcticrainforest** [comment]
I think this is solved now. Isn't it?

**Comment by eelucio** [comment]
No, is not working fully yet.

I just plotted with movieplotter that gives the outputs in gifs, e.g. [here](https://www.xces.dkrz.de/history/929956/results/)
the output is indeed a gif
`/work/bm1159/XCES/xces-work/k204229/evaluation_system/output/movieplotter/20240205_144228/929956/input1-psl_1hr_reanalysis_era5_r1i1p1_20210701-20210731.nc_nc3_SELDATE_psl_movie.gif`
but the preview is not
`/work/bm1159/XCES/xces-work/share/preview/20240205/movieplotter_20240205_154927_oQxKgkTN.gif`

however for mp4 it does work (e.g. with animator)
https://www.xces.dkrz.de/history/928784/results/

**Comment by eelucio** [comment]
the PR of #198 should close this issue
