### ISSUE TITLE
question about how the databrowser expands a filename (not urgent at all)

### ISSUE THREAD

**Issue by eelucio** [freva-org/freva-legacy#28]
in [_databrowser](https://github.com/FREVA-CLINT/freva/blob/75dd41cf572bb58374e063417ab3fdae8f25a7f3/src/freva/_databrowser.py#L207) we can see that when we enter the filename such as for example:
```
        import freva
        from pathlib import Path
        file = ".docker/data/observations/grid/CPC/CPC/cmorph/30min/atmos/30min/r1i1p1/v20210618/pr/pr_30min_CPC_cmorph_r1i1p1_201609020000-201609020030.nc"
        res = freva.databrowser(file=file, all_facets=True)
        print(res)
```

the filename is expanded using:

```
        # If we don't convert a str to a str mypy will complain.
        f = Path(str(search_facets["file"])).expanduser().absolute()
        search_facets["file"] = f'"\{f}"'
```

a couple of users noted that with their plugin shell scripts, when they were calling freva to get some facet information if they were doing

```
$ data=/work/ik1017/CMIP6/data/CMIP6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r10i1p1f1/day/uas/gn/v20190710/uas_day_MPI-ESM1-2-LR_historical_r10i1p1f1_gn_20100101-20141231.nc

$ freva databrowser file="\\$data" --facet=ensemble -vvv
DEBUG:freva:Searching dictionary: {'file': '"\\/usr/bin/\\/work/ik1017/CMIP6/data/CMIP6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r10i1p1f1/day/uas/gn/v20190710/uas_day_MPI-ESM1-2-LR_historical_r10i1p1f1_gn_20100101-20141231.nc"', 'time_select': 'Intersects', 'time': ''}

...

```
the two `\\` were interpreted in a different way as how it was working with the old freva:

` f = Path(str(search_facets["file"])).expanduser().absolute()` interprets "\/" as the path from which we are executing the plugin due to the `.absolute()` method

just in case some other user comes with this...

**Comment by antarcticrainforest** [comment]
So the problem is that the users were using `\\/path/to/filename`? 

That doesn't work. The question is what should we do about that?

**Comment by eelucio** [comment]
For the moment I just eliminated the "\\" in their shell scripts, next step will be to eliminate the freva calls from within the plugin themselves
